insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (1, 2303, 4505, 'punk', 'Serenade in the Rain', 'Dynamic Music Group', '54');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (2, 2833, 8584, 'dance', 'Harmony of the Heart', 'Starlight Music', '84');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (3, 4195, 718, 'hip hop', 'Dancing in the Moonlight', 'Rhythm Records', '61');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (4, 9346, 4812, 'jazz', 'Sunshine', 'Melody Records', '72');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (5, 4833, 6369, 'indie', 'Whispering Wind', 'Golden Note Productions', '52');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (6, 2501, 2291, 'metal', 'Echoes of Yesterday', 'Acme Records', '32');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (7, 6930, 4162, 'soul', 'Summer Breeze', 'Dynamic Music Group', '19');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (8, 9998, 2612, 'alternative', 'Rhythm of the Night', 'Harmony Entertainment', '65');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (9, 2912, 467, 'soul', 'Summer Breeze', 'Melodic Beats', '64');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (10, 5908, 8321, 'folk', 'Harmony of the Heart', 'Golden Note Productions', '56');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (11, 8677, 7338, 'blues', 'Midnight Serenade', 'Melody Records', '68');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (12, 5546, 3463, 'pop', 'Summer Breeze', 'Golden Note Productions', '74');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (13, 6183, 9121, 'soul', 'Melodies of Love', 'Golden Note Productions', '2');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (14, 9032, 7904, 'jazz', 'Serenade in the Rain', 'Golden Note Productions', '7');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (15, 3455, 7996, 'blues', 'Harmony of the Heart', 'Starlight Music', '16');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (16, 3189, 4522, 'folk', 'Serenade in the Rain', 'Sonic Records', '6');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (17, 4518, 594, 'electronic', 'Dancing in the Moonlight', 'Acme Records', '59');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (18, 9134, 1979, 'classical', 'Melodies of Love', 'Golden Note Productions', '21');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (19, 5925, 1164, 'hip hop', 'Serenade in the Rain', 'Melody Records', '10');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (20, 6179, 127, 'hip hop', 'Midnight Serenade', 'Sonic Records', '11');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (21, 7026, 6921, 'reggae', 'Rhythm of the Night', 'Acme Records', '57');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (22, 5653, 2536, 'punk', 'Midnight Serenade', 'Harmonious Sounds', '75');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (23, 2858, 4978, 'dance', 'Dancing in the Moonlight', 'Melodic Beats', '38');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (24, 6317, 7310, 'hip hop', 'Harmony of the Heart', 'Golden Note Productions', '83');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (25, 7028, 7683, 'country', 'Serenade in the Rain', 'Harmonious Sounds', '39');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (26, 1807, 6268, 'classical', 'Echoes of Yesterday', 'Harmony Entertainment', '53');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (27, 6494, 1370, 'folk', 'Whispering Wind', 'Sonic Records', '34');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (28, 3861, 8534, 'rock', 'Dancing in the Moonlight', 'Harmonious Sounds', '46');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (29, 5964, 7538, 'latin', 'Serenade in the Rain', 'Melodic Beats', '27');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (30, 3530, 2216, 'folk', 'Serenade in the Rain', 'Acme Records', '43');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (31, 5591, 8454, 'pop', 'Echoes of Yesterday', 'Acme Records', '12');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (32, 2899, 2132, 'latin', 'Harmony of the Heart', 'Harmonious Sounds', '42');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (33, 1584, 3061, 'jazz', 'Serenade in the Rain', 'Golden Note Productions', '73');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (34, 4546, 9620, 'r&b', 'Sunshine', 'Harmony Entertainment', '31');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (35, 5961, 8087, 'dance', 'Summer Breeze', 'Acme Records', '29');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (36, 638, 4414, 'latin', 'Midnight Serenade', 'Rhythm Records', '91');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (37, 6821, 9731, 'pop', 'Sunshine', 'Melody Records', '76');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (38, 3192, 1988, 'dance', 'Echoes of Yesterday', 'Acme Records', '77');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (39, 3956, 142, 'soul', 'Rhythm of the Night', 'Harmony Entertainment', '99');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (40, 5888, 3615, 'reggae', 'Echoes of Yesterday', 'Rhythm Records', '97');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (41, 3181, 7174, 'reggae', 'Dancing in the Moonlight', 'Dynamic Music Group', '71');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (42, 827, 7895, 'country', 'Rhythm of the Night', 'Acme Records', '15');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (43, 6126, 5028, 'classical', 'Whispering Wind', 'Melody Records', '98');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (44, 852, 9784, 'latin', 'Summer Breeze', 'Golden Note Productions', '24');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (45, 8316, 4495, 'country', 'Serenade in the Rain', 'Rhythm Records', '20');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (46, 5719, 4800, 'punk', 'Dancing in the Moonlight', 'Sonic Records', '90');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (47, 7856, 5351, 'dance', 'Melodies of Love', 'Starlight Music', '13');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (48, 5770, 2850, 'dance', 'Rhythm of the Night', 'Harmonious Sounds', '55');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (49, 5345, 4506, 'gospel', 'Dancing in the Moonlight', 'Harmonious Sounds', '82');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (50, 744, 6513, 'dance', 'Harmony of the Heart', 'Starlight Music', '4');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (51, 1982, 5793, 'reggae', 'Sunshine', 'Melody Records', '67');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (52, 8176, 9742, 'alternative', 'Summer Breeze', 'Starlight Music', '69');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (53, 2278, 367, 'alternative', 'Whispering Wind', 'Rhythm Records', '51');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (54, 101, 9388, 'metal', 'Serenade in the Rain', 'Melodic Beats', '37');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (55, 4047, 6302, 'folk', 'Echoes of Yesterday', 'Acme Records', '62');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (56, 4763, 3108, 'latin', 'Dancing in the Moonlight', 'Melodic Beats', '41');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (57, 7764, 3887, 'metal', 'Rhythm of the Night', 'Starlight Music', '79');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (58, 9526, 9354, 'gospel', 'Melodies of Love', 'Harmony Entertainment', '48');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (59, 7118, 2471, 'r&b', 'Echoes of Yesterday', 'Harmonious Sounds', '18');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (60, 2875, 6715, 'hip hop', 'Summer Breeze', 'Sonic Records', '94');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (61, 3295, 1346, 'indie', 'Sunshine', 'Dynamic Music Group', '95');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (62, 2658, 2621, 'dance', 'Rhythm of the Night', 'Harmonious Sounds', '9');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (63, 5108, 3757, 'r&b', 'Melodies of Love', 'Melody Records', '66');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (64, 6586, 1676, 'classical', 'Rhythm of the Night', 'Melody Records', '49');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (65, 4191, 2233, 'r&b', 'Dancing in the Moonlight', 'Melodic Beats', '70');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (66, 1239, 53, 'blues', 'Summer Breeze', 'Starlight Music', '14');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (67, 4190, 6929, 'country', 'Sunshine', 'Melodic Beats', '17');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (68, 2941, 8850, 'classical', 'Midnight Serenade', 'Harmonious Sounds', '92');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (69, 3941, 2430, 'alternative', 'Harmony of the Heart', 'Melodic Beats', '80');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (70, 1589, 6635, 'electronic', 'Whispering Wind', 'Starlight Music', '35');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (71, 9405, 4644, 'rap', 'Echoes of Yesterday', 'Acme Records', '81');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (72, 1714, 9238, 'r&b', 'Melodies of Love', 'Harmonious Sounds', '36');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (73, 5956, 9560, 'reggae', 'Midnight Serenade', 'Acme Records', '8');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (74, 3403, 2913, 'reggae', 'Whispering Wind', 'Dynamic Music Group', '93');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (75, 9427, 2584, 'indie', 'Echoes of Yesterday', 'Melodic Beats', '89');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (76, 7013, 9077, 'dance', 'Midnight Serenade', 'Starlight Music', '40');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (77, 6292, 2897, 'r&b', 'Echoes of Yesterday', 'Melodic Beats', '33');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (78, 7277, 2715, 'hip hop', 'Whispering Wind', 'Melodic Beats', '25');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (79, 9513, 32, 'electronic', 'Whispering Wind', 'Starlight Music', '45');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (80, 2265, 6789, 'reggae', 'Sunshine', 'Harmonious Sounds', '58');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (81, 5749, 9287, 'pop', 'Echoes of Yesterday', 'Starlight Music', '100');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (82, 9470, 1478, 'latin', 'Melodies of Love', 'Melodic Beats', '1');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (83, 9653, 9360, 'electronic', 'Harmony of the Heart', 'Melody Records', '63');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (84, 4326, 6283, 'r&b', 'Harmony of the Heart', 'Sonic Records', '30');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (85, 1615, 443, 'reggae', 'Rhythm of the Night', 'Harmonious Sounds', '22');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (86, 2985, 5928, 'folk', 'Summer Breeze', 'Harmony Entertainment', '28');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (87, 402, 5711, 'punk', 'Summer Breeze', 'Starlight Music', '88');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (88, 9115, 6613, 'electronic', 'Melodies of Love', 'Dynamic Music Group', '96');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (89, 234, 7866, 'gospel', 'Whispering Wind', 'Harmony Entertainment', '26');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (90, 9217, 6189, 'alternative', 'Dancing in the Moonlight', 'Golden Note Productions', '50');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (91, 4431, 4812, 'blues', 'Harmony of the Heart', 'Melodic Beats', '5');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (92, 8563, 4622, 'soul', 'Dancing in the Moonlight', 'Harmonious Sounds', '47');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (93, 8681, 4722, 'indie', 'Melodies of Love', 'Golden Note Productions', '87');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (94, 6011, 6237, 'indie', 'Harmony of the Heart', 'Harmony Entertainment', '3');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (95, 3146, 258, 'indie', 'Summer Breeze', 'Rhythm Records', '44');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (96, 1976, 1280, 'indie', 'Dancing in the Moonlight', 'Golden Note Productions', '23');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (97, 7476, 4535, 'pop', 'Sunshine', 'Golden Note Productions', '78');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (98, 9759, 1622, 'alternative', 'Serenade in the Rain', 'Golden Note Productions', '85');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (99, 1812, 805, 'rock', 'Whispering Wind', 'Golden Note Productions', '60');
insert into SongCatalog (catalogID, totalSales, value, genre, name, companyID, songID) values (100, 6387, 3936, 'classical', 'Melodies of Love', 'Dynamic Music Group', '86');
